Python Django/FirstProject/FirstProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/',include('polls.urls', namespace="polls")),
]

Python Django/FirstProject/polls/urls.py
from django.conf.urls import url
from .import views

urlpatterns=[
    url(r'^$',views.index,name="index"),
    url(r'^(?P<question_id>[0-9]+)$',views.detail,name="detail"),
    url(r'^(?P<question_id>[0-9]+)/results$',views.results,name="results"),
    url(r'^(?P<question_id>[0-9]+)/vote$',views.vote,name="vote"),

]

Python Django/FirstProject/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text= models.CharField(max_length=200)
    pub_date= models.DateTimeField('data published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    question= models.ForeignKey(Question,on_delete=models.CASCADE)
    def __str__(self):
        return self.choice_text

Python Django/FirstProject/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    latest_questions = Question.objects.order_by('-pub_date')[:5]
    # to load a template
    context ={
        'latest_question':latest_questions
    }
    return render(request,'polls/index.html',context)

def detail(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    return render(request,'polls/detail.html',{'question':question})

def results(request, question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})

def vote(request, question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except:
        return render(request,'polls/detail.html',{'question': question,'error_message':"Please select choice"})
    else:
        selected_choice.votes+=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

Python Django/FirstProject/polls/templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" type="text/css"href="{%static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css"href="{%static 'polls/style.css'%}" />
</head>
<body>
<hr>
<p> Header </p>
<hr>
{% include "polls/header.html" %}
<div class="jumbotron">
      <div class="container">

        {% block main_content %}
        {% endblock %}
        {% include "polls/footer.html" %}
      </div>
</div>

</body>
</html>

Python Django/FirstProject/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block main_content %}
<h1> {{question.question_text}} </h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" class="btn btn-success"value="vote">
</form>
<a href="{% url 'polls:index'%}">Back to question list</a>

{% endblock %}

Python Django/FirstProject/polls/templates/polls/footer.html
<footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>

Python Django/FirstProject/polls/templates/polls/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

Python Django/FirstProject/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block main_content %}
<h1> Choose a question </h1>
{% if latest_question %}
    <ul>
        {% for question in latest_question %}
            <li><a href= {% url "polls:detail" question.id %}><b>{{question.question_text}}</b></a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>You don't have any questions.Please add</p>
{% endif %}

{% endblock %}

Python Django/FirstProject/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block main_content %}
<h1> {{question.question_text}} </h1>
<ul>
    {%for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}--{{choice.votes}} vote{{ choice.votes | pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}"> Vote Again</a>
{% endblock %}